name: "Optic"
description: "Run Optic against the current commit"
inputs:
  optic_token:
    description: "Your organization's Optic token"
    required: true
  github_token:
    description: "A GitHub token that can append comments to a PR"
    required: true
  standards_fail:
    description: "Fail the action if a standard fails"
    required: false
    default: "true"
  additional_args:
    description: "Additional arguments to pass into `diff-all`"
    required: false
runs:
  using: "node16"
  main: "build/index.js"
