name: "Optic"
description: "Run Optic against the current commit"
inputs:
  token:
    description: "Your organization's Optic token"
    required: true
  base:
    description: The base branch that you want to run a comparison against. Defaults to master
    default: master
runs:
  using: "node16"
  main: "build/index.js"
