name: "Optic"
description: "Run Optic against the current commit"
inputs:
  optic_token:
    description: "Your organization's Optic token to use Optic cloud"
    required: false
  github_token:
    description: "A GitHub token that can append comments to a PR"
    required: true
  compare_from_push:
    description: "Set the ref to compare from in push events"
    required: false
  compare_from_pr:
    description: "Set the ref to compare from in pull request events"
    required: false
  standards_fail:
    description: "Fail the action if a standard fails"
    required: false
    default: "true"
  additional_args:
    description: "Additional arguments to pass into `diff-all`"
    required: false
runs:
  using: "node16"
  main: "build/index.js"
