name: "Optic"
description: "Run Optic against the current commit"
inputs:
  token:
    description: "Your organization's Optic token"
    required: true
runs:
  using: "node16"
  main: "build/index.js"
