name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - uses: actions/checkout@v3
      - run: yarn

      - run: yarn run ci:lint
      - run: yarn run ci:test
      - run: yarn run ci:build
